# docker 
sudo: required
# docker cli required
services:
  - docker
# Use dockerfile.dev
before_install:
  - docker build -t washable-alt/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true washable-alt/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-567448487139"
  bucket_path: "docker-react"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"