services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile.dev
    ports:
      -  "3006:3006"
    volumes: 
      - /app/node_modules
      - .:/app
  # Running a second service and building a second container
  tests: 
    build:
      context: . 
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    # Overwrite npm run start command in Dockerfile
    command: ["npm", "run", "test"]
  